In [11]:
import pandas as pd
from sqlalchemy import create_engine

In [12]:
DATABASE_URL = "postgresql://postgres:1234@localhost:5432/bank_reviews"
engine = create_engine(DATABASE_URL)

df = pd.read_csv("../data/processed/final_reviews.csv")
df.head()

,review_id,review_text,sentiment_label,sentiment_score,identified_theme
0,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,POSITIVE,0.999851,Other
1,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,POSITIVE,0.999839,Other
2,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,POSITIVE,0.999851,Other
3,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,POSITIVE,0.999816,Other
4,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,POSITIVE,0.999873,Other

In [13]:
banks = pd.read_sql("SELECT * FROM banks", engine)
banks

   bank_id bank_name          app_name
0        1       BOA        BOA Mobile
1        2       CBE        CBE Mobile
2        3    Dashen  Dashen Super App

In [8]:
reviews = pd.read_sql("SELECT * FROM reviews LIMIT 10", engine)
reviews

,review_id,bank_id,review_text,rating,review_date,sentiment_label,sentiment_score,identified_theme,source
0,1,1,was Good 🙏,3,2025-01-01,POSITIVE,0.999851,Other,Google Play
1,2,1,Its Good,3,2025-01-01,POSITIVE,0.999839,Other,Google Play
2,3,1,cool,3,2025-01-01,POSITIVE,0.999851,Other,Google Play
3,4,1,good,3,2025-01-01,POSITIVE,0.999816,Other,Google Play
4,5,1,it's very good app,3,2025-01-01,POSITIVE,0.999873,Other,Google Play
5,6,1,this app is good but the speed of app is very ...,3,2025-01-01,NEGATIVE,-0.995230,Performance Issues,Google Play
6,7,1,good,3,2025-01-01,POSITIVE,0.999816,Other,Google Play
7,8,1,boa the best,3,2025-01-01,POSITIVE,0.999843,Other,Google Play
8,9,1,bank of absiniya is best bank in ethiopian,3,2025-01-01,POSITIVE,0.999774,Other,Google Play
9,10,1,አስተማማኝና ዘመኑን የዋጀ,3,2025-01-01,NEGATIVE,-0.833725,Other,Google Play

In [14]:
query = """
SELECT b.bank_name, COUNT(*) AS total_reviews
FROM reviews r
JOIN banks b
ON r.bank_id = b.bank_id
GROUP BY b.bank_name
"""

pd.read_sql(query, engine)

  bank_name  total_reviews
0       BOA            500
1    Dashen            500
2       CBE            500